# Generated by Django 5.2.8 on 2025-11-25 21:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwningSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(blank=True, choices=[('PERSON', 'Person'), ('GROUP', 'Group'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], max_length=16, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('symbol', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('decimals', models.PositiveSmallIntegerField(help_text='Number of fractional digits used for this unit.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('CASH_WALLET', 'Cash wallet'), ('BANK_ACCOUNT', 'Bank account'), ('PHYSICAL_ASSETPhysical Asset', 'Physical Asset'), ('INVESTMENT_ACCOUNTINVESTMENT_ACCOUNT', 'Investment Account'), ('CARD_ACCOUNT', 'Card Account'), ('LIABILITY_ACCOUNT', 'Liability Account'), ('CRYPTO_WALLET', 'Crypto Wallet'), ('OTHER', 'Other')], max_length=64)),
                ('external_id', models.CharField(blank=True, help_text='IBAN, last4, etc.', max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_sources', to='finances.owningsubject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_sources', to='finances.unit')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='finances.owningsubject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Warsaw', max_length=64)),
                ('locale', models.CharField(default='pl_PL', max_length=16)),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=8)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='finances.owningsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subject', 'role'], name='finances_su_subject_81ad6d_idx')],
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Always positive. Direction is implied by type.', max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(choices=[('HOME_MAINTENANCE', 'Home & maintenance'), ('FOOD_GROCERIES', 'Food & groceries'), ('HOUSEHOLD_UTILITIES', 'Household & utilities'), ('CLOTHES_EDC', 'Clothes & EDC'), ('MOBILITY_TRANSPORT', 'Mobility & Transport'), ('FUN_TRAVEL', 'Fun & Travel'), ('LIFESTYLE_HOBBY', 'Lifestyle & Hobby'), ('WORK_EDUCATION', 'Work & Education'), ('BUSINESS_FINANCE', 'Business & Finance'), ('TAX_FEES', 'Tax & Fees'), ('GIFTS_FAMILY', 'Gifts & Family'), ('OTHER', 'Other')], max_length=32)),
                ('from_asset_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='finances.assetsource')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.owningsubject')),
                ('to_asset_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='finances.assetsource')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.unit')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['subject', 'occurred_at'], name='finances_tr_subject_56e587_idx'), models.Index(fields=['type'], name='finances_tr_type_db9430_idx'), models.Index(fields=['category'], name='finances_tr_categor_0d5e70_idx'), models.Index(fields=['project'], name='finances_tr_project_5d93fd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'), models.CheckConstraint(condition=models.Q(models.Q(('type', 'INCOME'), ('to_asset_source__isnull', False), ('from_asset_source__isnull', True)), models.Q(('type', 'EXPENSE'), ('from_asset_source__isnull', False), ('to_asset_source__isnull', True)), models.Q(('type', 'TRANSFER'), ('from_asset_source__isnull', False), ('to_asset_source__isnull', False)), _connector='OR'), name='transaction_from_to_by_type'), models.CheckConstraint(condition=models.Q(models.Q(('type', 'TRANSFER'), _negated=True), models.Q(('from_asset_source', models.F('to_asset_source')), _negated=True), _connector='OR'), name='transaction_transfer_from_ne_to')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24, validators=[django.core.validators.MinValueValidator(1e-12)])),
                ('valid_at', models.DateTimeField()),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='finances.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='finances.unit')),
            ],
            options={
                'ordering': ['-valid_at'],
                'indexes': [models.Index(fields=['from_unit', 'to_unit', 'valid_at'], name='finances_ex_from_un_591ecd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_unit', models.F('to_unit')), _negated=True), name='exchange_rate_from_ne_to')],
                'unique_together': {('from_unit', 'to_unit', 'valid_at')},
            },
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['subject', 'active'], name='finances_as_subject_f1c547_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['unit'], name='finances_as_unit_id_e17348_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsource',
            unique_together={('subject', 'name')},
        ),
    ]
